#!/bin/bash
src="$1"
dest="${2:-secure}"

auto_exec='cat "$0"|sed "1,3d"|openssl enc -d -aes-256-cbc -pbkdf2|. /dev/stdin "$@";exit'
vomit="$(echo "$auto_exec" | "$(dirname "$0")/obfuscate")"

cat <(echo '#!/usr/bin/env bash') <(echo "$vomit") <(openssl enc -aes-256-cbc -salt -pbkdf2 -in "$src") > "$dest"

chmod ug+x "$dest"
